package adf.sample.model;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 23 14:12:13 CET 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_DEPARTMENTS = 0;

    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsViewRowImpl() {
    }

    /**
     * Gets Departments entity object.
     * @return the Departments
     */
    public EntityImpl getDepartments() {
        return (EntityImpl)getEntity(0);
    }


    /**
     * Sample exportable method.
     */
    public void sampleDepartmentsViewRowImplExportable() {
    }

    /**
     * Sample exportable method.
     */
    public void sampleDepartmentsViewRowImplExportable2(String testParam1) {
    }
}
