package adf.sample.model;

import adf.sample.model.common.DepartmentsView;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.Row;
import oracle.jbo.Transaction;
import oracle.jbo.server.Entity;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 23 13:14:45 CET 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsViewImpl extends ViewObjectImpl implements DepartmentsView {
    private static ADFLogger LOGGER =ADFLogger.createADFLogger(DepartmentsViewImpl.class);
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsViewImpl() {
    }
    
    public String getRowStatus(Row row){
        DepartmentsViewRowImpl rwImpl = (DepartmentsViewRowImpl)row;
        String rwStatus = translateStatusToString(rwImpl.getEntity(0).getEntityState());
        LOGGER.finest(">>>>>> Row  Status:"+rwStatus);
        return rwStatus;
    }
    
    private String translateStatusToString(byte b) {
      String ret = null;
      switch (b) {
        case Entity.STATUS_INITIALIZED: {
          ret = "Initialized";
          break;
        }
        case Entity.STATUS_MODIFIED: {
          ret = "Modified";
          break;
        }
        case Entity.STATUS_UNMODIFIED: {
          ret = "Unmodified";
          break;
        }
        case Entity.STATUS_NEW: {
          ret = "New";
          break;
        }
      }
      return ret;
    }
}
