package adf.sample.model.common;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 23 14:14:41 CET 2008
// ---------------------------------------------------------------------
public interface DepartmentsView extends ViewObject {
    String getRowStatus(Row row);
}
